-- SQL script to import drug products
-- Manufacturer ID = 1

INSERT INTO drug_products (name, active_ingredient, dosage, unit, category, image_url, description, storage_conditions, shelf_life, status, manufacturer_id, created_at, updated_at) VALUES
-- 1. Kháng sinh – thuốc kê đơn
('Augmentin 1g', 'Amoxicillin + Acid Clavulanic', '875mg/125mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/00000213_augmentin_1g_gsk_2x7_6846_6396_1638843194.jpg', 'Kháng sinh phổ rộng điều trị nhiễm khuẩn đường hô hấp, tiết niệu, da và mô mềm.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),
('Klamentin 625', 'Amoxicillin + Acid Clavulanic', '500mg/125mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/dsc_0528_403c4f796d.jpg', 'Kháng sinh phối hợp điều trị nhiễm khuẩn nhạy cảm với Amoxicillin.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),
('Klamentin 1g', 'Amoxicillin + Acid Clavulanic', '875mg/125mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/00018596_klamentin_1g_duoc_hau_giang_2x7_5475_6207_1637731778.jpg', 'Kháng sinh hàm lượng cao cho các nhiễm khuẩn nặng đường hô hấp, tiết niệu.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),
('Zinnat 500mg', 'Cefuroxim axetil', '500mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/00003460_zinnat_500mg_hang_nhap_khau_1v_6380_6339_1633512301.jpg', 'Kháng sinh nhóm Cephalosporin thế hệ 2 điều trị nhiễm khuẩn hiệu quả.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '36 tháng', 'active', 1, NOW(), NOW()),
('Medoclav 1g', 'Amoxicillin + Acid Clavulanic', '875mg/125mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/00000002_medoclav_1g_medochemie_2x7_5568_6142_1634629452.jpg', 'Kháng sinh phối hợp giúp chống lại vi khuẩn kháng thuốc.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),
('Cefixim 200mg', 'Cefixim', '200mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/00001037_cefixim_200mg_3x10_cuu_long_5177_6118_1633514757.jpg', 'Kháng sinh Cephalosporin thế hệ 3, dùng cho nhiễm khuẩn hô hấp và tiết niệu.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '36 tháng', 'active', 1, NOW(), NOW()),
('Cefuroxim 500mg', 'Cefuroxim', '500mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/00000300_cefuroxim_500mg_vidipha_2x5_5548_6097_1634542284.jpg', 'Điều trị các nhiễm khuẩn do vi khuẩn nhạy cảm gây ra.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '36 tháng', 'active', 1, NOW(), NOW()),
('Levofloxacin 500mg', 'Levofloxacin', '500mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/00007887_levofloxacin_500mg_pymepharco_2x10_8147_6151_1637731777.jpg', 'Kháng sinh nhóm Fluoroquinolone cho nhiễm khuẩn nặng hô hấp và da.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '36 tháng', 'active', 1, NOW(), NOW()),
('Moxifloxacin 400mg', 'Moxifloxacin', '400mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/00007843_moxifloxacin_400mg_pymepharco_1x10_3735_6169_1637731779.jpg', 'Kháng sinh phổ rộng điều trị viêm phổi và các nhiễm khuẩn phức tạp.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '36 tháng', 'active', 1, NOW(), NOW()),
('Azithromycin 500mg', 'Azithromycin', '500mg', 'Viên', 'Kháng sinh – thuốc kê đơn', 'https://cms-prod.s3-sgn09.fptcloud.com/00021614_azithromycin_500mg_stada_1x3_7994_6010_1633512306.jpg', 'Kháng sinh nhóm Macrolide điều trị nhiễm khuẩn hô hấp, liều ngắn ngày.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),

-- 2. Thuốc dạ dày – tiêu hóa
('Nexium 40mg', 'Esomeprazol', '40mg', 'Viên', 'Thuốc dạ dày – tiêu hóa', 'https://cms-prod.s3-sgn09.fptcloud.com/00000052_nexium_40mg_astrazeneca_2x7_5365.jpg', 'Thuốc ức chế bơm proton điều trị trào ngược dạ dày (GERD) và viêm loét.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '36 tháng', 'active', 1, NOW(), NOW()),
('Esomeprazol STADA 40mg', 'Esomeprazol', '40mg', 'Viên', 'Thuốc dạ dày – tiêu hóa', 'https://cms-prod.s3-sgn09.fptcloud.com/00021615_esomeprazol_stada_40mg_stada_4x7_5474_6010_1633513303.jpg', 'Giảm tiết acid dạ dày, hỗ trợ điều trị viêm loét và HP.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),
('Pantoprazol 40mg', 'Pantoprazol', '40mg', 'Viên', 'Thuốc dạ dày – tiêu hóa', 'https://cms-prod.s3-sgn09.fptcloud.com/00009653_pantoprazol_stada_40mg_stada_4x7_8984_6168.jpg', 'Thuốc ức chế bơm proton thế hệ mới, điều trị loét dạ dày tá tràng.', 'Nơi khô, dưới 30 độ C, tránh ánh sáng.', '36 tháng', 'active', 1, NOW(), NOW()),
('Gaviscon hộp', 'Natri alginate, Natri bicarbonat, Calci carbonat', 'Hỗn dịch', 'Hộp', 'Thuốc dạ dày – tiêu hóa', 'https://cms-prod.s3-sgn09.fptcloud.com/00010903_gaviscon_dual_action_r_10ml_24v_7366.jpg', 'Tạo lớp màng bảo vệ ngăn chặn trào ngược acid dạ dày, giảm ợ nóng.', 'Nơi khô, dưới 30 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),
('Enterogermina', 'Bacillus clausii', '2 tỷ bào tử', 'Ống', 'Thuốc dạ dày – tiêu hóa', 'https://cms-prod.s3-sgn09.fptcloud.com/00004944_enterogermina_2ty_5ml_20_ong_8223.jpg', 'Men vi sinh bổ sung lợi khuẩn, phòng và điều trị rối loạn tiêu hóa.', 'Nơi khô, dưới 30 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),
('BioGaia Probiotic', 'Lactobacillus reuteri Protectis', '5ml', 'Chai', 'Thuốc dạ dày – tiêu hóa', 'https://cms-prod.s3-sgn09.fptcloud.com/00501192_biogaia_protectis_baby_drops_5ml_1863.jpg', 'Men vi sinh từ Thụy Điển giúp cải thiện hệ tiêu hóa cho trẻ em.', 'Bảo quản dưới 25 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),
('Smecta hộp', 'Diosmectite', '3g', 'Hộp', 'Thuốc dạ dày – tiêu hóa', 'https://cms-prod.s3-sgn09.fptcloud.com/00014059_smecta_v_cam_chanh_30g_7718.jpg', 'Thuốc hấp phụ bảo vệ niêm mạc đường tiêu hóa, điều trị tiêu chảy.', 'Nơi khô, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Biosubtyl-II', 'Bacillus subtilis', '1 tỷ bào tử', 'Gói', 'Thuốc dạ dày – tiêu hóa', 'https://cms-prod.s3-sgn09.fptcloud.com/00000405_biosubtyl_ii_dalat_25_goi_x_1g_1411_6345.jpg', 'Vi khuẩn sống có lợi cho đường ruột, hỗ trợ tiêu hóa.', 'Nơi khô, dưới 30 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),

-- 3. Thuốc ho – hô hấp – siro
('Prospan Siro', 'Cao khô lá thường xuân', '100ml', 'Chai', 'Thuốc ho – hô hấp – siro', 'https://cms-prod.s3-sgn09.fptcloud.com/00000941_siro_ho_prospan_100ml_3756.jpg', 'Siro ho thảo dược giúp long đờm, giảm ho cho trẻ em và người lớn.', 'Nơi khô, dưới 25 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Muhi Siro trẻ em', 'Chiết xuất thảo dược', '120ml', 'Chai', 'Thuốc ho – hô hấp – siro', 'https://cms-prod.s3-sgn09.fptcloud.com/wellbaby_multi_vitamin_liquid_vitabiotics_ho_tro_suc_khoe_cho_be_150ml_7909_6372_1625907409.jpg', 'Siro ho Nhật Bản với các hương vị dễ uống dành cho trẻ em.', 'Nơi khô, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),
('Astex Siro', 'Húng chanh, Núc nác, Cineol', '90ml', 'Chai', 'Thuốc ho – hô hấp – siro', 'https://cms-prod.s3-sgn09.fptcloud.com/00000490_siro_ho_astex_90ml_4091_6339.jpg', 'Siro ho thảo dược bệnh viện Nhi Đồng 1 sản xuất.', 'Nơi khô, dưới 30 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),
('Bổ phế Nam Hà chai', 'Cát cánh, Tỳ bà diệp, Mơ muối...', '125ml', 'Chai', 'Thuốc ho – hô hấp – siro', 'https://cms-prod.s3-sgn09.fptcloud.com/00001099_thuoc_ho_bo_phe_nam_ha_chi_khai_lo_125ml_4366.jpg', 'Thuốc ho đông dược truyền thống giúp bổ phế, chỉ khái.', 'Nơi khô, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Eugica Siro', 'Eucalyptol, Gừng, Tần, Menthol', '100ml', 'Chai', 'Thuốc ho – hô hấp – siro', 'https://cms-prod.s3-sgn09.fptcloud.com/00000412_siro_ho_eugica_100ml_1752.jpg', 'Siro ho thảo dược giúp sát trùng đường hô hấp, làm dịu cơn ho.', 'Nơi khô, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),
('Toplexil Siro', 'Oxomemazine, Guaifenesin', '125ml', 'Chai', 'Thuốc ho – hô hấp – siro', 'https://cms-prod.s3-sgn09.fptcloud.com/00024479_siro_toplexil_sanofi_125ml_8700.jpg', 'Thuốc trị ho có đờm và ho khan do kích ứng.', 'Nơi khô, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),

-- 4. Thuốc tim mạch – huyết áp – mỡ máu
('Plavix 75mg', 'Clopidogrel', '75mg', 'Viên', 'Thuốc tim mạch – huyết áp – mỡ máu', 'https://cms-prod.s3-sgn09.fptcloud.com/00001859_plavix_75mg_28v_6221.jpg', 'Thuốc chống kết tập tiểu cầu, phòng ngừa đột quỵ và nhồi máu cơ tim.', 'Nơi khô, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Crestor 10mg', 'Rosuvastatin', '10mg', 'Viên', 'Thuốc tim mạch – huyết áp – mỡ máu', 'https://cms-prod.s3-sgn09.fptcloud.com/00000055_crestor_10mg_astrazeneca_2x14_9495.jpg', 'Thuốc hạ mỡ máu nhóm Statin hiệu quả cao.', 'Nơi khô, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Crestor 20mg', 'Rosuvastatin', '20mg', 'Viên', 'Thuốc tim mạch – huyết áp – mỡ máu', 'https://cms-prod.s3-sgn09.fptcloud.com/00005597_crestor_20mg_astrazeneca_2x14_6380.jpg', 'Mức liều 20mg cho bệnh nhân mỡ máu cao nặng.', 'Nơi khô, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Coveram', 'Perindopril + Amlodipin', '5mg/5mg', 'Viên', 'Thuốc tim mạch – huyết áp – mỡ máu', 'https://cms-prod.s3-sgn09.fptcloud.com/00021319_coveram_5mg_5mg_servier_1x30_8932.jpg', 'Thuốc phối hợp điều trị tăng huyết áp vô căn.', 'Nơi khô, dưới 30 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),
('Concor 5mg', 'Bisoprolol fumarate', '5mg', 'Viên', 'Thuốc tim mạch – huyết áp – mỡ máu', 'https://cms-prod.s3-sgn09.fptcloud.com/00003023_concor_5mg_merck_3x10_8698.jpg', 'Thuốc chẹn beta điều trị huyết áp và suy tim.', 'Nơi khô, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Lipitor 20mg', 'Atorvastatin', '20mg', 'Viên', 'Thuốc tim mạch – huyết áp – mỡ máu', 'https://cms-prod.s3-sgn09.fptcloud.com/00005598_lipitor_20mg_pfizer_3x10_4509.jpg', 'Thuốc ức chế HMG-CoA reductase hạ cholesterol toàn phần và LDL.', 'Nơi khô, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Vastarel MR 35mg', 'Trimetazidine', '35mg', 'Viên', 'Thuốc tim mạch – huyết áp – mỡ máu', 'https://cms-prod.s3-sgn09.fptcloud.com/00001097_vastarel_mr_35mg_servier_2x30_3136.jpg', 'Phòng ngừa cơn đau thắt ngực ổn định.', 'Nơi khô, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),

-- 5. Vitamin – thực phẩm chức năng
('Blackmores Multivitamin', 'Vitamin & Khoáng chất', 'Nhiều loại', 'Chai', 'Vitamin – thực phẩm chức năng', 'https://cms-prod.s3-sgn09.fptcloud.com/00502127_vien_uong_blackmores_mens_performance_multi_bo_sung_vitamin_cho_nam_gioi_50_vien_8350.jpg', 'Thực phẩm bảo vệ sức khỏe bổ sung vitamin tổng hợp.', 'Nơi khô ráo, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Doppelherz Aktiv Omega 3', 'Dầu cá (EPA, DHA), Vitamin E', '2000mg dầu cá', 'Chai', 'Vitamin – thực phẩm chức năng', 'https://cms-prod.s3-sgn09.fptcloud.com/00021669_doppelherz_omega_3_seefischol_1000mg_30_vien_2041_6339.jpg', 'Hỗ trợ sức khỏe tim mạch, não bộ và thị lực.', 'Nơi khô ráo, dưới 25 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Nature Made Vitamin C', 'Vitamin C', '500mg', 'Chai', 'Vitamin – thực phẩm chức năng', 'https://cms-prod.s3-sgn09.fptcloud.com/00021626_nature_made_vitamin_c_500mg_100_vien_9984_6339.jpg', 'Tăng khả năng miễn dịch và chống oxy hóa cho cơ thể.', 'Nơi khô ráo, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('DHC Collagen', 'Collagen peptide từ cá', '2050mg', 'Gói', 'Vitamin – thực phẩm chức năng', 'https://cms-prod.s3-sgn09.fptcloud.com/00024484_vien_uong_collagen_dhg_30_ngay_3277.jpg', 'Bổ sung collagen hỗ trợ làm đẹp da, tăng đàn hồi.', 'Nơi khô ráo, tránh ánh sáng.', '36 tháng', 'active', 1, NOW(), NOW()),
('Centrum A-Z', 'Vitamin & Khoáng chất', 'Đa vitamin', 'Chai', 'Vitamin – thực phẩm chức năng', 'https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/451433/item/vngoods_12_451433.jpg', 'Bổ sung đầy đủ vi chất dinh dưỡng hàng ngày.', 'Nơi khô ráo, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),
('Pharmaton', 'G115, Vitamin & Khoáng chất', 'Viên nang', 'Chai', 'Vitamin – thực phẩm chức năng', 'https://cms-prod.s3-sgn09.fptcloud.com/00001098_pharmaton_vitality_60_vien_7190.jpg', 'Tăng cường sức khỏe khi mệt mỏi, kén ăn, suy nhược.', 'Nơi khô ráo,ưới 30 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),
('NattoEnzym 670FU', 'Nattokinase', '670FU', 'Chai', 'Vitamin – thực phẩm chức năng', 'https://cms-prod.s3-sgn09.fptcloud.com/00021634_nattoenzym_670fu_duoc_hau_giang_3x10_8698_6339.jpg', 'Hỗ trợ tuần hoàn máu, giải tán cục máu đông, phòng đột quỵ.', 'Nơi khô ráo, dưới 30 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),
('Bocalex Multi', 'Vitamin B + C', 'Viên sủi', 'Tuýp', 'Vitamin – thực phẩm chức năng', 'https://cms-prod.s3-sgn09.fptcloud.com/00018597_bocalex_multi_20_vien_sui_7553.jpg', 'Viên sủi bổ sung vitamin nhanh chóng phục hồi thể lực.', 'Nơi khô ráo, tránh ẩm.', '24 tháng', 'active', 1, NOW(), NOW()),
('Daily-Vits', 'Vitamin & Khoáng chất', 'Đa vitamin', 'Chai', 'Vitamin – thực phẩm chức năng', 'https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/451433/item/vngoods_12_451433.jpg', 'Bổ sung dinh dưỡng thiết yếu duy trì sức khỏe tổng thể.', 'Nơi khô ráo, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Apisatone', 'Sữa ong chúa, mật ong, vitamin', '10ml', 'Hộp', 'Vitamin – thực phẩm chức năng', 'https://cms-prod.s3-sgn09.fptcloud.com/00000490_siro_ho_astex_90ml_4091_6339.jpg', 'Thuốc bổ chứa sữa ong chúa giúp bồi bổ cơ thể, tăng sức đề kháng.', 'Nơi khô ráo, dưới 30 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),

-- 6. Sản phẩm trẻ em – men – bổ sung
('Pediakid Vitamin', '22 Vitamin & Oligo-elements', '125ml', 'Chai', 'Sản phẩm trẻ em – men – bổ sung', 'https://cms-prod.s3-sgn09.fptcloud.com/00502127_vien_uong_blackmores_mens_performance_multi_bo_sung_vitamin_cho_nam_gioi_50_vien_8350.jpg', 'Bổ sung vitamin và khoáng chất cho trẻ từ 6 tháng tuổi.', 'Nơi khô ráo, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('Fitobimbi Siro', 'Chiết xuất thảo dược Italy', '200ml', 'Chai', 'Sản phẩm trẻ em – men – bổ sung', 'https://cms-prod.s3-sgn09.fptcloud.com/00021634_nattoenzym_670fu_duoc_hau_giang_3x10_8698_6339.jpg', 'Nhóm siro thảo dược Italy hỗ trợ bé ăn ngon, ngủ ngon.', 'Nơi khô ráo, dưới 30 độ C.', '36 tháng', 'active', 1, NOW(), NOW()),
('BioAmicus Vitamin D3', 'Vitamin D3 nguyên chất', '10ml', 'Chai', 'Sản phẩm trẻ em – men – bổ sung', 'https://cms-prod.s3-sgn09.fptcloud.com/00501192_biogaia_protectis_baby_drops_5ml_1863.jpg', 'Vitamin D3 tinh khiết không mùi không vị cho trẻ sơ sinh.', 'Nơi khô ráo, dưới 25 độ C.', '24 tháng', 'active', 1, NOW(), NOW()),
('ChildLife Multivitamin', 'Vitamin & Khoáng chất dạng lỏng', '237ml', 'Chai', 'Sản phẩm trẻ em – men – bổ sung', 'https://cms-prod.s3-sgn09.fptcloud.com/00001037_cefixim_200mg_3x10_cuu_long_5177_6118_1633514757.jpg', 'Cung cấp 23 loại vitamin và khoáng chất cần thiết nhất cho trẻ.', 'Nơi khô ráo, tránh ánh sáng.', '24 tháng', 'active', 1, NOW(), NOW()),
('Wellbaby Syrup', '14 Vitamin & Khoáng chất, Mạch nha', '150ml', 'Chai', 'Sản phẩm trẻ em – men – bổ sung', 'https://cms-prod.s3-sgn09.fptcloud.com/wellbaby_multi_vitamin_liquid_vitabiotics_ho_tro_suc_khoe_cho_be_150ml_7909_6372_1625907409.jpg', 'Siro bổ sung kẽm, sắt và vitamin cho sự phát triển của bé.', 'Bảo quản nơi khô ráo, dưới 25 độ C.', '36 tháng', 'active', 1, NOW(), NOW());
